apiVersion: v1
kind: Namespace
metadata:
  name: kafka-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-app
data:
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-0.kafka-headless.kafka-app.svc.cluster.local:9093"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
#  KAFKA_CFG_NUM_PARTITIONS: "3"
#  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_CFG_LOG_RETENTION_HOURS: "168"
  ALLOW_PLAINTEXT_LISTENER: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-app
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka-app
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: server
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-app
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        kafka-node-id: "1"
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.1
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-headless.kafka-app.svc.cluster.local:9092"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1G -Xms512M"
          ports:
            - containerPort: 9092
              name: server
            - containerPort: 9093
              name: controller
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
      volumes:
        - name: data
          emptyDir: { }