apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka-app
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 9093
              name: controller
          envFrom:
            - configMapRef:
                name: kafka-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
              - name: kafka-data
                mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data