apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-app
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP # Only ClusterIP needed with Ingress