services:
  app-prod-ca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-prod-ca
    ports:
      - "9000:9000"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - kafka-network
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"

      # Listeners conf
      KAFKA_CFG_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"

      # KRaft specific
      KAFKA_KRAFT_CLUSTER_ID: "WmXm0ALxT5y5w3lYKw0DkA"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Security (development only)
      ALLOW_PLAINTEXT_LISTENER: "yes"

      # Other configs
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-network

networks:
  kafka-network: