apiVersion: v1
kind: Service
metadata:
  name: app-prod-service
  namespace: kafka-app
  labels:
    app: app-prod
spec:
  selector:
    app: app-prod
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
